Parameterize the command

diff --git a/sh/status b/sh/status
--- a/sh/status
+++ b/sh/status
@@ -2,9 +2,9 @@
 
 # Run a command and use a background process to report status
 
-cmd() { sleep 5; exit 24; }
+cmd() { sleep $1; exit $2; }
 
-cmd &   # Run the long running process
+cmd ${1-3} ${2-1}&   # Run the long running process
 pid=$!  # Record the pid
 
 # Spawn a process that coninually reports that the command is still running
@@ -15,8 +15,8 @@ echoer=$!
 trap 'kill $echoer' 0
 
 # Wait for the process to finish
-if wait $pid; status=$?; echo; then
-    echo "cmd succeeded"
+if wait $pid; then
+    printf "\ncmd succeeded\n"
 else
-    echo "cmd FAILED!! (returned $status)" >&2
+    printf "\ncmd FAILED!! (returned $?)\n" >&2
 fi
