Look for executable in . and builddir
This is super hacky.  The framework will execute the script in
srcdir with the builddir as working directory, but it is convenient
to be able to execute the tests manually while sitting in the srcdir.
Sort of.  Probably better to avoid trying to add this functionality.

diff --git a/c/bst-test b/c/bst-test
--- a/c/bst-test
+++ b/c/bst-test
@@ -1,6 +1,17 @@
 #!/bin/sh
-BUILDDIR=build/$(uname -s)/$(uname -m)
-out=$( printf 'foo bar baz' | "${BUILDDIR}"/bst )
+
+for dir in . "build/$(uname -s)/$(uname -m)"; do
+	if test -f $dir/bst; then
+		exe=$dir/bst
+		break
+	fi
+done
+if test -z "$exe" || ! test -x "$exe"; then
+	echo 'Cannot find executable' >&2
+	exit 1
+fi
+
+out=$( printf 'foo bar baz' | "$exe" )
 expect='bar: {1:1}
 baz: {1:1}
 foo: {1:1}'
