Do not test directories.  Cleanup err message

diff --git a/c/read-test b/c/read-test
--- a/c/read-test
+++ b/c/read-test
@@ -9,12 +9,14 @@ if ! test "$out" = 'rab oof
 owt eno';
 then echo "Got $out" >&2; exit 1; fi
 
-if ! test "$( printf abc | $exe )" = cbq; then
-	die "Failed on single line with no newline"
+got=$( printf abc | $exe )
+if ! test "$got" = cba; then
+	die "Failed on single line with no newline.  Got '$got', expected cba"
 fi
 
 count=0
 for i in *.c *; do
+	test -f "$i" || continue
 	: $(( count += 1 ))
 	if ! $exe "$i" | $exe | cmp - "$i"; then
 		echo "Okay on $count files, but failed on $i" >&2
